
env:
  TERM: alacritty
window:
  padding:
    x: 2
    'y': 2
  dynamic_padding: false
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: None
scrolling:
  history: 10000
  multiplier: 1
font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 12
  offset:
    x: 0
    'y': 0
  glyph_offset:
    x: 0
    'y': 0
draw_bold_text_with_bright_colors: false
colors:
  primary:
    background: '#2E3440'
    foreground: '#D8DEE9'
  normal:
    black: '#3B4252'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#88C0D0'
    white: '#E5E9F0'
  bright:
    black: '#4C566A'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#8FBCBB'
    white: '#ECEFF4'
bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'
window.opacity: 1
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false
dynamic_title: true
cursor:
  style: Underline
  unfocused_hollow: true
live_config_reload: true
working_directory: None
mouse:
  double_click:
    threshold: 300
  triple_click:
    threshold: 300
  hints:
    launcher:
      program: xdg-open
      args: []
    modifiers: None
mouse_bindings:
  - mouse: Middle
    action: Copy
key_bindings:
  - key: P
    mods: Control
    action: Paste
  - key: Insert
    mods: Shift
    action: Paste
  - key: Slash
    mods: Control
    chars: gc
  - key: 'Y'
    mods: Control
    action: Copy
  - key: Key0
    mods: Control
    action: ResetFontSize
  - key: Equals
    mods: Control
    action: IncreaseFontSize
  - key: Plus
    mods: Control
    action: IncreaseFontSize
  - key: Minus
    mods: Control
    action: DecreaseFontSize
debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
