#! /bin/sh

sxhkd &
xinput set-prop "DELL07E6:00 06CB:76AF Touchpad" "libinput Tapping Enabled" 1 &
setxkbmap -option caps:escape &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d terminal web workspace git music 6 7

# mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"
#
# bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10
# bspc desktop -f 1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
